### ISSUE TITLE
Consider the backup plan before parachain onboarding

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/research-force#109]
The slack-originated discussion should be continued here.

The topic was started by @hanwencheng :

> want to discuss the possibility about this strategy:
> 1. First run Litentry network with our own validators
> 2. Attend parachain and submit a basic wasm in the crowdloan
> 3. When we win the slot, we switch our independent network to a parachain, upgrade the wasm with existed network, if failed, still run with our own validators

It's all about the usability of our future products before the official parachain goes online.

**Comment by Kailai-Wang** [comment]
Here are the discussions in slack so far:

@h4n0 

The whole plan sounds to me overall complicated, because we have never investigated and thought in this direction, and there are some blockers in my mind that I think we need to find out solutions for. Also to other colleagues, please feel free to provide your opinions if I am wrong.
1. For point 1, we need to think about the security plan, especially if all validators are run by ourselves. If we allow others to join our validation process, we need to take time to test and verify this feature.
2. For point 3, if we 'switch' from a standalone network to a parachain, should we shutdown the previous network? Or run both parallel? If we shut the old one down, we ought to migrate all on chain states to the parachain, which IMHO, it's not easy. WASM is just the state transition function and it does not contain any states, nor onchain tx, storage etc. Even if it's possible, how to deal with the old one's validators, if they are from community?

Overall, I think it would be expensive in terms of development, operation and research.
***
@suinuj 

difficult for standalone to be parachain. it is easier to run a relay-chain by ourself, then switch to Kusama or Polkadot.
***
@Kailai-Wang 

Personally I'm unwilling to go after this strategy:
- state migration between (para-)chains is generally complex and very error-prone
- dev cost is doubled or even trippled: we have to maintain 2 chains plus the migration/sync
- More communication overhead with community: it could take quite some time to convince them firstly using our own chain and then moving to a parachain
But I also understand that we'd like to have users starting to use our product once it's ready-to-go, even without an official parachain.

Maybe some ideas at first thought:
1. Can we have alpha-test with our staging env? The data will not be transferred to the parachain later, but the alpha-users will get rewards/airdrops.
2. in case the testing focus lies outside of parachain behavior, can we do the trial run in a more centralised way? In this case the data will be migrated to parachain later. Data migration should be easier than whole state migration.
***
@hanwencheng 

The purpose of having a parachain is not to dry-run for testing, but not make parachain a bottleneck for the upcoming products. So consider the two options you proposed:
 1. staging env: this is sensible to me, but in this case the on-chain activities are temporary. Like NFTs, and also the LIT token is not used.
2. trial run: I am not fully understand this way. In this case do we still have a blockchain? or use a centralized database to record everything?
***
@Kailai-Wang 

Understood.
To option 2 I originally meant a centralized DB as I thought it was about a single product.  This option could have been ruled out if we have multiple products which all use parachain as a basic platform.
Option 1 can help test the water but doesn't preserve any on-chain state.
In either way we are working on compromises, IMHO the most ideal way is still an official parachain.

Perhaps some more alternatives:
3. we launch a Kusama parachain and put our main activities there until we win a polkadot parachain slot
4. we use staging env until we win a polkadot parachain slot, but we only promise partial migration (e.g. we only migrate the account balance and NFT related info, but not the whole chain state).

**Comment by qiuhaiguo** [comment]
The final discussion on whether to create a standalone chain or a parachain on Kusama resulted in a preference for a parachain chain on Kusama for the following reasons：

1. the security requirements for maintaining the standalone chain are very high
2. the technical requirements for the standalone chain are also very high
3. the event and extrinsic will be lost during the migration from the standalone chain to the parachain, and only the balance and some other states will be saved in the end, but not the whole chain state

**Comment by Kailai-Wang** [comment]
We are onboarding kusama parachain (litmus), this one can be closed for now.
