### ISSUE TITLE
define Kusama parachain name and optional token symbol (Kitentry? KIT?)

### ISSUE THREAD

**Issue by geastwood** [litentry/research-force#112]

**Comment by geastwood** [comment]
**KIT** is too much resemble **KILT**

**Comment by geastwood** [comment]
How about **LITK**?

**Comment by Kailai-Wang** [comment]
LITK is not bad to me, not sure it has to match the final chain name though.
But I'm probably fine with whichever it's decided :P

**Comment by hanwencheng** [comment]
Close as decided with Litmus with LIT.

**Comment by geastwood** [comment]
FYI: @Kailai-Wang
