### ISSUE TITLE
LIT token allocation on ERC20 and Litmus discussion and token bridge model discussion

### ISSUE THREAD

**Issue by qiuhaiguo** [litentry/research-force#118]
- [ ] We need to decide LIT token balance distribution on Litmus and ERC20
- [ ] Token migration model discussion
-  Add mint() and burn() method in token migration pallet to keep the token balance integrity between Litmus and ERC20
-  Use sudo to set balance on the token bridge address to prevent some security issues

**Comment by geastwood** [comment]
https://github.com/litentry/crowdloan-distributor

This is what @h4n0 been working on.

**Comment by Kailai-Wang** [comment]
@geastwood 
I believe this is more about the tokeneconomics plan which might change the way of using bridge (and thus the code change), the following questions should be answered IMO:

- do we have a rough idea of how to allocate the LIT total supply (100,000,000)?
- do we have a predefined upper bound for the circulated LIT on a certain chain? If/how can this number be changed?
- On parachain side, how do we transfer the balance, from some pot or something like mint()?
- Error handling for security risks: what to do if it exceeds the preset limit? What to do if we observe abnormal transfer?
- How extensible is the plan in the future? Imagine we want bi-directional, we want inflation...

There are quite some details.

**Comment by Kailai-Wang** [comment]
This is one of the longest titles that I have seen 😁

**Comment by wangminqi** [comment]
If we use burn/mint method, the security risk should be same as "Use sudo to set balance on the token bridge address". No more and no less good.
We can force the pallet_balance totalSupply check for each extrinsic token_bridge related and check after the mint/burn, the totalSupply have to be less than a restriction.

This should be same as we use sudo to set balance on the token bridge address. The max loss is the restriction we set = the balance sudo set for token bridge.

Restriction can be modified by a democracy root call, same as sudo set_balance democarcy root call again in possible future when the parachain system need more token in circulating supply.

So I consider dynamic mint/burn is an overall better alternative compared to only a fixed amount of token minted in token bridge address. As dynamic mint/burn is more straight forward and intuitive without bringing extra security risk.

**Comment by Kailai-Wang** [comment]
Do we have enough information now?
If so, could you please clear up the doc a bit? @qiuhaiguo 
We are going to open another issue for implementation/adaption.

**Comment by qiuhaiguo** [comment]
I think @suinuj has already added new tasks for token bridge. I will clear the doc today. Let's close this issue.
https://www.notion.so/litentry/Token-bridge-summary-bb2d64d116f941ca934156e309abb97c
