### ISSUE TITLE
Crowdloan claim documentation

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#121]
Once the f/e UI is ready, the crowdloan doc shall be added in the documentation. The following points shall be described:

- [ ] How much can you get
- [ ] How long will it last
- [ ] How to claim for the vested crowdloan

**Comment by qiuhaiguo** [comment]
https://www.notion.so/litentry/How-to-claim-LIT-on-Litmus-67651d51a1664fcbbbeeee26611040c4

**Comment by geastwood** [comment]
Will this eventually being published on our documentation site?

**Comment by qiuhaiguo** [comment]
Already published on our docs site. https://docs.litentry.com/parachain/user-documentation/how-to-claim-crowdloan-rewards
