### ISSUE TITLE
Determine collation fee (with management board)

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#26]

**Comment by qiuhaiguo** [comment]
Feedback from discussion

 Block Reward

1. collator roadmap：
       Phase 1: POA, collator are managed by ourself 
       Phase 2: POS，Allow the community to run the collator
       Phase 3: Begin nominating and staking from our community

Transaction Fee
1. 40 % of each block's transactions fees will be allocated to the treasury
2. The remaining percentage of the fees are burned

https://www.notion.so/litentry/Collator-fee-research-9caccb8e770b4749a55895ed7d05bfcf
