### ISSUE TITLE
Collators deployment for production env

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#35]
Blocked before 3 weeks that we are going to go live 
- [x] Deploy a multiple collator blockchain network
(not all nodes are collator nodes, we also need say rpc nodes)

**Comment by chenzongxiong** [comment]
I set up 3 nodes, (ssl, domain name, lb, account are setup)

| domain | IP |
|--------|-------|
| parachain-sg-1.litentry.io | 13.251.110.168 |
| parachain-sg-2.litentry.io  | 13.251.110.168 |
| parachain-sg-3.litentry.io | 13.212.147.223 | 

exposed public RPC endpoint **wss://parachain.litentry.io**

**Comment by chenzongxiong** [comment]
@Kailai-Wang  bootnodes

```
--bootnodes /dns/parachain-sg-1.litentry.io/tcp/40333/p2p/12D3KooWBy6nNAuca2ZrxNEH93bzmb7ZjRpzRbbz7CtNEraiHtSC

--bootnodes /dns/parachain-sg-2.litentry.io/tcp/40333/p2p/12D3KooWJejFQVK5wtZeDZguAXkzQxngrS9yZt2F1bk92m5w4Xgp

--bootnodes /dns/parachain-sg-3.litentry.io/tcp/40333/p2p/12D3KooWD3ovhokyzvB4k8q6XhSiBrfySz2qzzNdj6SeqaUcFLga
```

**Comment by Kailai-Wang** [comment]
This is resolved.
