### ISSUE TITLE
More research on service.rs and rpc.rs in cumulus node/ codes

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/research-force#39]
A follow-up issue of https://github.com/litentry/research-force/issues/27

More investigation should be taken to look into details of [service.rs](https://github.com/paritytech/cumulus/blob/master/polkadot-parachains/src/service.rs) and [rpc.rs](https://github.com/paritytech/cumulus/blob/master/polkadot-parachains/src/rpc.rs) from cumulus codes.

A summay should be composed to describe which parts can be beneficial to us / which parts we are missing.

**Comment by Kailai-Wang** [comment]
RPC doc: https://www.notion.so/litentry/More-research-on-rpc-rs-82bdf20e4b404ddfbcf0940cc8401c74

**Comment by Kailai-Wang** [comment]
Service doc: https://www.notion.so/litentry/More-research-on-service-rs-7101ca28ebbf4a96b3e3e18f71ac5665
(might have more contents later)

**Comment by h4n0** [comment]
<=10min
