### ISSUE TITLE
Learn the 'node' implementation from other parachains

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/research-force#40]
A follow-up issue of https://github.com/litentry/research-force/issues/27

As suggested in https://www.notion.so/litentry/monitoring-plan-e69606c20d1145fea2175cb3b2f184d3

Learning of `node` implementation from other parachains (live and to-be-live) should be helpful.
It's meant to be a high-level walkthrough to study their patterns and see if we can benefit from them.

A sum-up is required.

**Comment by Kailai-Wang** [comment]
Summary: https://www.notion.so/litentry/Summary-of-node-researches-of-other-parachains-af7c434d27674e7b868e7666cc0ac777
Overall an interesting research.

I move it to "Discussion" -- I need to discuss it with @Satoshi-Kusumoto either soon or after I finish #39

**Comment by h4n0** [comment]
<=10min
