### ISSUE TITLE
Determine Testing environments

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#47]
- [x] Clarify if westend and chachacha are currently available to use
- [x] Decide if an extra staging env is required (self-hosted relay chain and parachain) litentry/litentry-parachain#109
- [ ] Add auto deployment to westend/staging env into CI of parachain

**Comment by h4n0** [comment]
According to parity, rococo will be back soon. We can use rococo as testnet over westend because westend is aimed at those who are will to onboard kusama as a temporary solution.

**Comment by Kailai-Wang** [comment]
regarding chachacha:
I talked with Sato and came into the conlusion that using chachacha has mainly the following 2 advantages:
- you don't have to run and maintain the relay chain nodes yourself ( - maintenance overhead)
- you have the chance to cooperate with third party projects 

But nothing specific about chachacha chain itself.
