### ISSUE TITLE
Genesis distribution

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#59]
- [ ] Write a plan/ instruction how to add sudoer initial distribution into genesis

**Comment by qiuhaiguo** [comment]
https://www.notion.so/litentry/Genesis-token-issuance-abd2e2f9e32c40e7ab9e4c39bf180554

**Comment by h4n0** [comment]
<=10min

**Comment by Satoshi-Kusumoto** [comment]
Give 4 (3 collator + 1 sudoer) accounts 100 initial lit
