### ISSUE TITLE
[DevOps] Parachain runtime upgrade investigation.

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#6]
Blocked until we have a preliminary runable parachain

Acceptance Criteria

- [x] Investigate the method of Parachain runtime upgrade from other projects 
- [x] Write step-by-step guide in notion of how it works
- [x] ~~If possible, provide a script of upgrading automation~~ 
       _won't do IMHO, see comment below_

**Comment by Kailai-Wang** [comment]
Doc:
https://www.notion.so/litentry/Parachain-runtime-upgrade-a2d6cfcd99b14bd79de3b766faed0e52

Experiments of runtime-upgrade were made on the staging chain:
- using `system.set_code`
- using `parachainSystem.authorize_upgrade`

Scripting the upgrade automation is considered as an overkill, as manual execution is not complicated and even safer (e.g. you are clearly aware that you are executing via sudo)

**Comment by h4n0** [comment]
30min
