### ISSUE TITLE
Weight and Fee implementation

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/research-force#61]
- [x] Identify parts (transaction fee, collator rewards, staking rewards
- [x] Collect other projects' way (weightToFee, FeeMultiplierUpdate from pallet_transaction_payment) @wangminqi 
- [ ] Related possibilities summary @wangminqi @qiuhaiguo 
- [ ] plan in documentation
- [ ] implementation

**Comment by wangminqi** [comment]
Other projects' transaction payment summary document
https://www.notion.so/litentry/Runtime-Fee-Related-Logic-3fb772564cec448cb99f361edb94a513

**Comment by h4n0** [comment]
<=10min
