### ISSUE TITLE
Determine collective details

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/research-force#63]
How many committee, how to initialize (using membership or collective itself), what's the initial members
Because parachain does not have election pallet, if without membership pallet, it can only be changed by root?
- [x] Study and summary other's implementation 
- [x] discussion
- [ ] plan + new issue creation

**Comment by Kailai-Wang** [comment]
**Doc:**
https://www.notion.so/litentry/Parachain-collective-details-48a8fc79f0b74d93abfa2bb42a401cf5

**Quotes:**
From my perspective the most traditional and safest way is to use membership to control council and tech-committee, ofc the operating origin of membership has to be bound to councils. In this way:

- we have the control on our own hands (via council)
- easier to manipulate the collective, compared to no-membership.

Elections *could* be activated once we decide to allow community to take partin the governance in the future.
