### ISSUE TITLE
Run runtime benchmark

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/research-force#67]
- [x] Run a preliminary trial on our machine (Democracy, System, Balance, Utility) and compare with original weights
- [x] The pallets are chosen and added into the runtime-benchmarks list (determined by the trial)
- [x] Fix machine spec
- [x] Run once
- [x] Import the weight files

**Comment by Kailai-Wang** [comment]
@suinuj 
The docker image was built: `litentry/litentry-parachain:runtime-benchmarks`
Alternatively you could simply use the binary that was archived by [this action job](https://github.com/litentry/litentry-parachain/actions/runs/1364499600).

**Comment by suinuj** [comment]
benchmark executed in 54.255.141.181, and the result in https://github.com/litentry/litentry-parachain/tree/benchmark-test/source.

**Comment by suinuj** [comment]
frame_system
extrinsic litentry substrate
remark 140_695_000  574_000
set_heap_pages 6_962_000 1_891_000
set_changes_trie_config 12_737_000 7_370_000
kill_prefix 13_010_000 7_616_000

balances
extrinsic litentry substrate
transfer 105_887_000 70_952_000
transfer_keep_alive 77_626_000 54_410_000
set_balance_creating 41_745_000 29_176_000
set_balance_killing 50_743_000  35_214_000
force_transfer 103_400_000 71_780_000
transfer_all 95_251_000 66_475_000
force_unreserve() 39_519_000 27_766_000

utility
extrinsic litentry substrate
batch 32_569_000 30_319_000
as_derivative 7_157_000 4_030_000
batch_all 32_257_000 26_621_000
