### ISSUE TITLE
Regular research list

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/research-force#68]
- [x] Polkadot 0.9.13 [updates](https://github.com/paritytech/polkadot/releases/tag/v0.9.13) (pairing study) 
- [x] 2021.11 Monthly key [PRs](https://mp.weixin.qq.com/s/q4gVtRzfoveD4AIt9gzPew) @Satoshi-Kusumoto @h4n0 @Kailai-Wang  (+[Eco tech](https://mp.weixin.qq.com/s/SbRVJHQw2Fb-wbZf89nw-w))

- [ ] transaction pool @Kailai-Wang 

- [x] multi token support research @wangminqi 

- [x] frame-support
- [x] orml (minor, do it slowly)

Ready to share:
- [x] parachain crowdloan/auctions @wangminqi 
- [x] xcm-executor @wangminqi 
- [x] xcm-builder @wangminqi 
- [ ] service initialization @suinuj

**Comment by wangminqi** [comment]
Too old. And most finished.
