### ISSUE TITLE
Parachain docker/devops presentation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/research-force#73]
It's scheduled for Oct.19 to have a presentation for the parachain deployment.

The following aspects should be taken into consideration:
- general build/deploy workflow
- introduction to different env based on different chain specs: NFT, dev/CI, staging
- show around the env: polkadot-JS, docker hub, live-demo if applicable
- how are artifacts generated
- plans for the next step/future

A PPT would be beneficial.
@chenzongxiong feel free to supplement.

**Comment by geastwood** [comment]
Make it simple, don't over spend time on it.

**Comment by Kailai-Wang** [comment]
Presented.
Related doc: https://www.notion.so/litentry/Parachain-Docker-deployment-overview-ec5f4957d554488c955ebbe7fe9a65ff
