### ISSUE TITLE
Pressure and intensive test on production network

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#76]
This story is a follow-up one from #9 

We need to add test cases to be able to simulate the following scenarios:

Test Cases | Performace Monitor
100 tx/s | CPU loads/memory loads/network usage
1000 tx/s | CPU loads/memory loads/network usage

A script should be written to fetch the CPU/memory loads every second (or from grafana dashboard) as a test report.

Transactions can be composed of simple balance transfers or other extrinsic calls (which may have higher weights)

Test plan shall be updated as well accordingly.

**Comment by Kailai-Wang** [comment]
This tool may help:
https://github.com/paritytech/sub-flood

**Comment by h4n0** [comment]
Tested locally, see the report here:
https://www.notion.so/litentry/Pressure-test-with-sub-flood-598e875446db4b8b9bbc35823354b416

**Comment by h4n0** [comment]
Tested locally, see the report here:
https://www.notion.so/litentry/Pressure-test-with-sub-flood-598e875446db4b8b9bbc35823354b416
