### ISSUE TITLE
Sync with Subscan about our litmus parachain

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#81]

**Comment by geastwood** [comment]
Probably we can expand the scope of this issue also to check [Ankr](https://www.ankr.com/). They also have similar services. 

Plus if I remember correctly they use to offer this one-click eth2 validator setup. I can imagine it's gonna be good for us to let our community boot up litentry node.

**Comment by Kailai-Wang** [comment]
@chenzongxiong do you know if we still need this for Litmus? If so, how to proceed?

also tagging @geastwood @qiuhaiguo

**Comment by geastwood** [comment]
I think we need this for Litmus. Have to contact them to set it up.

**Comment by geastwood** [comment]
@Kailai-Wang can we also add this into our litmus onboard checklist?

**Comment by Kailai-Wang** [comment]
The original checklist #110 was closed.

I'll compose a post-launch checklist and add this issue to it.

**Comment by Kailai-Wang** [comment]
Who has contact to `subscan`? Who shall follow up on this? @geastwood @chenzongxiong 
Or is it something we need to decide between ANKR and subscan? Or can we use it both?

AFAIU I just need subscan as block explorer?

**Comment by Kailai-Wang** [comment]
Assigned to @qiuhaiguo

**Comment by Kailai-Wang** [comment]
Subscan would need a dedicated archive node for their RPC queries.
We'll need to launch a new EC2 instance.

**Comment by Kailai-Wang** [comment]
Deployed and submitted: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-subscan.litmus-parachain-sg.litentry.io#/explorer

We are waiting for feedback from subscan.

**Comment by qiuhaiguo** [comment]
Litmus explorer is already online on the Subscan https://litmus.subscan.io/
