### ISSUE TITLE
priliminary balance transfer monitor

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/research-force#84]
1. list all potential balance changing events
2. monitor and alert if the changes exceeds a threshold (a warning log and an alert, 2 threshold)
3. Slack notification integration
Additionaly, if able to actively monitor all the account balance change will be better (since not all changes is revealed as an Event)

Write a more detailed (rough) plan first

**Comment by wangminqi** [comment]
Too old.
