### ISSUE TITLE
Provide the crowdloan participant list 

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#90]
A Litentry Polkadot crowdloan participant list shall be provided:

1. The list can be a JSON format, or any other equivalent format, containing every participant's address and the amount of DOT he/she contributes.
2. The list shall include all participants from Polkadot JS App, Parallel and Bifrost.

**Comment by Moehringen** [comment]
@Shihao66 is doing the same job and the API already.

**Comment by h4n0** [comment]
@Shihao66 Could you provide a list of Litmus crowdloan participants?

**Comment by Kailai-Wang** [comment]
should be provided, @h4n0 could you please confirm this?

**Comment by geastwood** [comment]
@Shihao66 can you confirm you have seen this? And it's being worked on?

**Comment by geastwood** [comment]
https://squid.litentry.io/graphql
```
query MyQuery {
  substrateCrowdloanContributions(where: {paraId_eq: 2106}) {
    amount
    rootAccount
    account {
      id
    }
    id
  }
}
```

`litentry-graph` can also query the data, for reference.

**Comment by Kailai-Wang** [comment]
We should be able to compare those two results against each other, and against polkadot-js too.

Set priority to medium as the data is basically there and it just needs to be double-checked after @h4n0 returns from the vacation.

The crowdloan distribution is expected to happen after a few weeks after litmus goes live, so we still have enough time.

**Comment by h4n0** [comment]
I've already got the data from @Shihao66 weeks ago. 
To make it safer, I would suggest either litentry graph or web3go can compare their crowdloan data with each other. And if the data are identical on both sides, I will start the distribution process soon.
@geastwood @bdmason @Shihao66

**Comment by Moehringen** [comment]
agree

**Comment by h4n0** [comment]
Created a [new issue](https://github.com/litentry/litentry-graph/issues/162) and assigned it to @geastwood and @bdmason . Feel free to assign it to the correct person.

**Comment by geastwood** [comment]
Yeh, @bdmason let's also provide the data from litentry-graph.

**Comment by geastwood** [comment]
@h4n0 you are quick, was about to create an issue on litentry-graph repo.

**Comment by bdmason** [comment]
The query at https://graph.litentry.io/graphql:

```graphql
query MyQuery {
  substrateCrowdloanContributions(where: {paraId_eq: 2106, network_eq: kusama}) {
    amount
    account {
      id
    }
    rootAccount
  }
}
```

@h4n0 I'll send you the result at a json file on slack

**Comment by h4n0** [comment]
https://github.com/litentry/litentry-graph/issues/162 has completed, thus this issue can be closed.
