### ISSUE TITLE
Next step planning of TEE

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#94]

**Comment by hanwencheng** [comment]
Let's have a planning session.

**Comment by h4n0** [comment]
Let's have a brief discussion on Thursday's weekly meeting with IntegriTEE team.

**Comment by h4n0** [comment]
Milestones have been updated here https://www.notion.so/litentry/TEE-Milestones-c14777c4bfd640bcaf25fb4f01f4a28f
