### ISSUE TITLE
Compensation List

### ISSUE THREAD

**Issue by hanwencheng** [litentry/research-force#99]
related to https://github.com/litentry/research-force/issues/90

In order to send compensation to Litentry's 1st batch participants, we need to get the list of all the participants with their contributions from Polkadot.js, Parallel, and Bifrost.

**Comment by h4n0** [comment]
Should we compensate them with LIT? But how could we do this without having our parachain onboarded?

**Comment by geastwood** [comment]
The solution has to be in a direction as follow
1. make it a claim process
2. before we onboard our parachain, we store in our DB, and give them an interface to check their entitlement. e.g. with this address __abc__, you can claim __x__ LIT

**Comment by h4n0** [comment]
Then I suggest storing the compensation data in the same DB where the contribution list is stored. We make a frontend app to enable users to check how many compensation LIT as well as the reward LIT they will receive once our chain is on board. 

After we go on board, we will distribute the rewards to each user according to the DB.

A claim process is not required according to our distribution plan.

**Comment by h4n0** [comment]
Already discussed this with @Shihao66 , and he will provide the crowdloan data as soon as our crowdloan ends.

About the compensation query interface that @geastwood mentioned, could @StamfordDigital @bdmason give some feedbacks about the feasibility to add this function on our crowdloan page?

**Comment by h4n0** [comment]
@hanwencheng @geastwood Should we build an interface to let users check their entitled rewards & compensation right after the current crowdloan ends? If yes, who should be responsible for the frontend development? The crowdloan will end in less than 2 days!

**Comment by hanwencheng** [comment]
would be good to have a minimum interface on the Litentry Web App.

**Comment by StamfordDigital** [comment]
I'll discuss this with @bdmason.
